<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

/**
 * Comando para generar el archivo JSON con las ubicaciones del Ecuador
 * Contiene provincias, cantones y parroquias oficiales del INEC
 */
class DescargarUbicaciones extends Command
{
    protected $signature   = 'ubicaciones:generar';
    protected $description = 'Genera el archivo JSON con provincias, cantones y parroquias del Ecuador';

    public function handle()
    {
        $ubicaciones = [
            "Azuay" => [
                "Cuenca" => ["Bellavista","Cañaribamba","El Batán","El Sagrario","El Vecino","Gil Ramírez Dávalos","Hermano Miguel","Huayna Cápac","Machángara","Monay","San Blas","San Sebastián","Sucre","Totoracocha","Yanuncay","Baños","Chaucha","Checa","Chiquintad","Llacao","Molleturo","Nulti","Octavio Cordero Palacios","Paccha","Quingeo","Ricaurte","San Joaquín","Santa Ana","Sayausí","Sinincay","Tarqui","Turi","Valle","Victoria del Portete"],
                "Girón" => ["Girón","Asunción","San Gerardo"],
                "Gualaceo" => ["Gualaceo","Colel","Daniel Córdova Toral","Jadán","Jima","Luis Cordero Vega","Mariano Moreno","Remigio Crespo Toral","San Juan","Zhidmad"],
                "Nabón" => ["Nabón","Cochapata","El Progreso","Las Nieves"],
                "Paute" => ["Paute","Bulán","Chicán","El Cabo","Guarainag","Tomebamba"],
                "Pucará" => ["Pucará","El Carmelo","Güel","La Asunción","San Rafael de Sharug"],
                "San Fernando" => ["San Fernando","Chumblín"],
                "Santa Isabel" => ["Santa Isabel","Abdón Calderón","El Carmen de Pijilí","Shaglly"],
                "Sigsig" => ["Sigsig","Cuchil","Gima","Jima","Ludo","San Bartolomé","San José de Raranga"],
                "Oña" => ["Oña","Susudel"],
                "Chordeleg" => ["Chordeleg","Delegsol","La Unión","Principal","Remigio Crespo","San Martín de Puzhío"],
                "El Pan" => ["El Pan","San Vicente"],
                "Sevilla de Oro" => ["Sevilla de Oro","Amaluza","Palmas"],
                "Guachapala" => ["Guachapala"],
                "Camilo Ponce Enríquez" => ["Camilo Ponce Enríquez","El Carmen de Pijilí","San Rafael de Sharug","Aurora"],
            ],
            "Bolívar" => [
                "Guaranda" => ["Guaranda","Ángel Polibio Chaves","Facundo Vela","Gabriel Ignacio de Veintimilla","Guanujo","Julio Moreno","Salinas","San Lorenzo","San Simón","Simiátug","Santa Fe","Telimbela"],
                "Chillanes" => ["Chillanes","San José del Tambo"],
                "Chimbo" => ["Chimbo","Asancoto","Cochabamba","La Magdalena","San José de Chimbo","San Pedro de Chandil","Santiago"],
                "Echeandía" => ["Echeandía"],
                "San Miguel" => ["San Miguel","Balsapamba","Bilován","Regulo de Mora","San Pablo","San Vicente","Santiago","Télimbela"],
                "Caluma" => ["Caluma"],
                "Las Naves" => ["Las Naves"],
            ],
            "Cañar" => [
                "Azogues" => ["Azogues","Aurelio Bayas","Borrero","Cojitambo","Guapán","Javier Loyola","Luis Cordero","Rivera","San Miguel","Taday"],
                "Biblián" => ["Biblián","Jerusalén","Nazón","San Francisco de Paguancay","Turupamba"],
                "Cañar" => ["Cañar","Chontamarca","Ducur","General Morales","Gualleturo","Honorato Vásquez","Ingapirca","Juncal","San Antonio","Ventura","Zhud"],
                "La Troncal" => ["La Troncal","Manuel J. Calle","Pancho Negro"],
                "El Tambo" => ["El Tambo"],
                "Déleg" => ["Déleg","Solano"],
                "Suscal" => ["Suscal"],
            ],
            "Carchi" => [
                "Tulcán" => ["Tulcán","El Carmelo","Julio Andrade","Maldonado","Pioter","Tobar Donoso","Tufiño","Urbina","Chical","Santa Martha de Cuba"],
                "Bolívar" => ["Bolívar","García Moreno","Los Andes","Monte Olivo","San Rafael","San Vicente de Pusir"],
                "Espejo" => ["El Ángel","El Goaltal","La Libertad","San Isidro"],
                "Mira" => ["Mira","Concepción","Jijón y Caamaño","Juan Montalvo"],
                "Montúfar" => ["San Gabriel","Chitan de Navarrete","Cristóbal Colón","Fernández Salvador","González Suárez","La Paz","Piartal"],
                "Sucumbíos" => ["La Bonita","El Playón de San Francisco","La Sofía","Rosa Florida","Santa Bárbara"],
            ],
            "Chimborazo" => [
                "Riobamba" => ["Riobamba","Cacha","Calpi","Cubijíes","Flores","Licán","Licto","Pungalá","Punín","Quimiag","San Juan","San Luis","Veloz","Velasco","Maldonado","Lizarzaburu"],
                "Alausí" => ["Alausí","Achupallas","Guasuntos","Huigra","Multitud","Pistishí","Pumallacta","Sevilla","Sibambe","Tixán"],
                "Colta" => ["Cajabamba","Cañi","Columbe","Juan de Velasco","Santiago de Quito"],
                "Chambo" => ["Chambo"],
                "Chunchi" => ["Chunchi","Compud","Gonzol","Llagos","Capsol"],
                "Guamote" => ["Guamote","Cebadas","Palmira"],
                "Guano" => ["Guano","Ilapo","La Providencia","San Andrés","San Gerardo","San Isidro de Patulú","San José de Chazo","Santa Fe de Galán","Valparaíso"],
                "Pallatanga" => ["Pallatanga"],
                "Penipe" => ["Penipe","El Altar","La Candelaria","Matus","Puela","San Antonio de Bayushig","Bilbao"],
                "Cumandá" => ["Cumandá"],
            ],
            "Cotopaxi" => [
                "Latacunga" => ["Latacunga","Aláquez","Belisario Quevedo","Guaytacama","Joseguango Bajo","Mulaló","11 de Noviembre","Pastocalle","Poaló","San Juan de Pastocalle","Tanicuchí","Toacaso"],
                "La Maná" => ["La Maná","El Triunfo","Guasaganda","Pucayacu"],
                "Pangua" => ["El Corazón","Moraspungo","Pinllopata","Ramón Campaña"],
                "Pujilí" => ["Pujilí","Angamarca","La Victoria","Pilaló","Tingo","Zumbahua"],
                "Salcedo" => ["San Miguel","Antonio José Holguín","Cusubamba","Mulalillo","Mulliquindil","Panzaleo"],
                "Saquisilí" => ["Saquisilí","Canchagua","Chantilín","Cochapamba"],
                "Sigchos" => ["Sigchos","Chugchilán","Isinliví","Las Pampas","Palo Quemado"],
            ],
            "El Oro" => [
                "Machala" => ["Machala","El Cambio","El Retiro","La Providencia","Jubones","Nueve de Mayo","Tendales"],
                "Arenillas" => ["Arenillas","Carcabón","Palmales","La Cuca"],
                "Atahualpa" => ["Paccha","Ayapamba","Cordoncillo","Milagros","San José","Uzhcurrumi"],
                "Balsas" => ["Balsas","Bellamaria"],
                "Chilla" => ["Chilla"],
                "El Guabo" => ["El Guabo","Barbones","La Iberia","Tendales","Río Bonito"],
                "Huaquillas" => ["Huaquillas","Arcapamba","Chacras","El Paraíso","Huaquillas","Milton Reyes"],
                "Marcabelí" => ["Marcabelí","El Ingenio"],
                "Pasaje" => ["Pasaje","Bolívar","Buenavista","Cañaquemada","El Progreso","La Peaña","Loma de Franco","Ochoa León","Uzhcurrumi"],
                "Piñas" => ["Piñas","Ayapamba","La Bocana","Moromoro","Piedras","San Roque","Saracay"],
                "Portovelo" => ["Portovelo","Curtincápac","Morales","Zaruma"],
                "Santa Rosa" => ["Santa Rosa","Bellavista","La Avanzada","Jambelí","San Antonio","Victoria"],
                "Zaruma" => ["Zaruma","Abañín","Arcapamba","Guanazán","Guizhaguiña","Huertas","Malvas","Muluncay","Sinsao","Salvias"],
                "Las Lajas" => ["Las Lajas"],
            ],
            "Esmeraldas" => [
                "Esmeraldas" => ["Esmeraldas","Atacames","Sua","Same","Tonsupa","Las Palmas","Simón Plata Torres","Luis Tello","5 de Agosto","Bartolomé Ruiz"],
                "Atacames" => ["Atacames","La Unión","Súa","Tonchigüe","Tonsupa"],
                "Eloy Alfaro" => ["Valdez","Borbón","La Tola","Limones","Luis Vargas Torres","Malimpia","Olmedo","San Francisco de Onzole","Selva Alegre","Telembí","Timbiré","Timbiquí","Wimbí"],
                "Muisne" => ["Muisne","Bolívar","Daule","Galera","La Unión","Quingue","Salima","San Francisco","San Gregorio","San José de Chamanga"],
                "Quinindé" => ["Rosa Zárate","Cube","Chura","La Unión","Malimpia","Viche"],
                "San Lorenzo" => ["San Lorenzo","Ancón de Sardinas","Carondelet","5 de Junio","Mataje","Santa Rita","Tambillo","Tululbí","Urbina"],
                "Rioverde" => ["Rioverde","Chontaduro","Chumundé","Lagarto","Montalvo"],
                "La Concordia" => ["La Concordia","La Independencia"],
            ],
            "Galápagos" => [
                "Isabela" => ["Puerto Villamil","Tomás de Berlanga"],
                "San Cristóbal" => ["Puerto Baquerizo Moreno","El Progreso","Santa María"],
                "Santa Cruz" => ["Puerto Ayora","Baltra","Bellavista","Santa Rosa"],
            ],
            "Guayas" => [
                "Guayaquil" => ["Guayaquil","Chongón","Juan Gómez Rendón","Morro","Posorja","Puná","Tenguel"],
                "Alfredo Baquerizo Moreno" => ["Juján"],
                "Balao" => ["Balao"],
                "Balzar" => ["Balzar"],
                "Colimes" => ["Colimes"],
                "Daule" => ["Daule","Juan Bautista Aguirre","Laurel","Limonal","Los Lojas"],
                "Durán" => ["Durán","El Recreo"],
                "El Empalme" => ["El Empalme","Guayas","Pelillo Negro"],
                "El Triunfo" => ["El Triunfo"],
                "Milagro" => ["Milagro","Chobo","Mariscal Sucre","Roberto Astudillo"],
                "Naranjal" => ["Naranjal","Jesús María","Santa Rosa de Flandes","Taura"],
                "Naranjito" => ["Naranjito"],
                "Nobol" => ["Narcisa de Jesús"],
                "Playas" => ["General Villamil"],
                "Samborondón" => ["Samborondón","La Puntilla"],
                "Santa Lucía" => ["Santa Lucía"],
                "Salitre" => ["General Lorenzo Vintimilla","Gral. Pedro J. Montero","La Victoria"],
                "San Jacinto de Yaguachi" => ["Yaguachi Nuevo","Cone","Gral. Pedro J. Montero","Virgen de Fátima"],
                "Simón Bolívar" => ["Simón Bolívar","Lorenzo de Garaicoa"],
                "Coronel Marcelino Maridueña" => ["Coronel Marcelino Maridueña"],
                "Lomas de Sargentillo" => ["Lomas de Sargentillo"],
                "Pedro Carbo" => ["Pedro Carbo","Sabanilla","Valle de la Virgen"],
                "Isidro Ayora" => ["Isidro Ayora"],
                "Palestina" => ["Palestina"],
                "Pedro Moncayo" => ["Tabacundo","La Esperanza","Malchinguí","Tocachi","Tupigachi"],
            ],
            "Imbabura" => [
                "Ibarra" => ["Ibarra","Alpachaca","Caranqui","El Sagrario","La Dolorosa del Priorato","Los Ceibos","Priorato","San Francisco","Victoria","Ambuquí","Angochahua","Carolina","La Esperanza","Lita","Salinas","San Antonio"],
                "Antonio Ante" => ["Atuntaqui","Andrade Marín","Imbaya","San Francisco de Natabuela","San José de Chaltura","San Roque"],
                "Cotacachi" => ["Cotacachi","Apuela","García Moreno","Imantag","Peñaherrera","Plaza Gutiérrez","Quiroga","Vacas Galindo","6 de Julio de Cuellaje"],
                "Otavalo" => ["Otavalo","Dr. Miguel Egas Cabezas","Eugenio Espejo","González Suárez","Pataquí","San José de Quichinche","San Juan de Ilumán","San Pablo","San Rafael","Selva Alegre"],
                "Pimampiro" => ["Pimampiro","Chugá","Mariano Acosta","San Francisco de Sigsipamba"],
                "San Miguel de Urcuquí" => ["Urcuquí","Cahuasquí","La Merced de Buenos Aires","Pablo Arenas","San Blas","Tumbabiro"],
            ],
            "Loja" => [
                "Loja" => ["Loja","Chantaco","Chuquiribamba","El Cisne","Gualel","Jimbilla","Malacatos","San Lucas","San Pedro de Vilcabamba","Sucre","Taquil","Vilcabamba","Yangana","Quinara"],
                "Calvas" => ["Cariamanga","Colaisaca","El Lucero","Utuana","San Vicente"],
                "Catamayo" => ["Catamayo","El Tambo","Guayquichuma","San Pedro de la Bendita","Zambi"],
                "Celica" => ["Celica","Cruzpamba","Pozul","Sabanilla","Tnte. Maximiliano Rodríguez Loaiza"],
                "Chaguarpamba" => ["Chaguarpamba","Buenavista","El Rosario","Lomopamba","Santa Rufina"],
                "Espíndola" => ["Amaluza","Bellavista","El Airo","Jimbura","Santa Teresita","27 de Abril"],
                "Gonzanamá" => ["Gonzanamá","Changaimina","Nambacola","Purunuma","Quilanga"],
                "Macará" => ["Macará","La Victoria","Larama","San Antonio"],
                "Paltas" => ["Catacocha","Cangonamá","Casanga","Guachanamá","La Tingue","Lauro Guerrero","Orianga","San Antonio","Yamana"],
                "Puyango" => ["Alamor","Ciano","El Arenal","El Limo","Mercadillo","Vicentino"],
                "Saraguro" => ["Saraguro","El Paraíso de Célén","El Tablon","Lluzhapa","Manú","San Antonio de Cumbe","San Pablo de Tenta","San Sebastián de Yuluc","Selva Alegre","Urdaneta","Yuluc"],
                "Sozoranga" => ["Sozoranga","Nueva Fátima","Tacamoros"],
                "Zapotillo" => ["Zapotillo","Cazaderos","Garzareal","Limones","Mangahurco","Paletillas"],
                "Pindal" => ["Pindal","Chaquinal","12 de Diciembre"],
                "Quilanga" => ["Quilanga","Fundochamba","San Antonio de las Aradas"],
                "Olmedo" => ["Olmedo","La Tingue"],
            ],
            "Los Ríos" => [
                "Babahoyo" => ["Babahoyo","Caracol","Clemente Baquerizo","El Salto","Febres Cordero","Pimocha","La Unión"],
                "Baba" => ["Baba","Guare","Isla de Bejucal"],
                "Montalvo" => ["Montalvo"],
                "Puebloviejo" => ["Puebloviejo","Puerto Pechiche","San Juan"],
                "Quevedo" => ["Quevedo","Guayabal","San Carlos"],
                "Urdaneta" => ["Catarama","Ricaurte"],
                "Ventanas" => ["Ventanas","El Rosario","Zapotal"],
                "Vinces" => ["Vinces","Antonio Sotomayor","Palenque"],
                "Palenque" => ["Palenque"],
                "Buena Fé" => ["Buena Fé","Patricia Pilar"],
                "Valencia" => ["Valencia"],
                "Mocache" => ["Mocache"],
                "Quinsaloma" => ["Quinsaloma"],
            ],
            "Manabí" => [
                "Portoviejo" => ["Portoviejo","Andrés de Vera","Colón","La Laguna","Picoazá","Pueblo Nuevo","Riochico","San Pablo","Crucita","Guangala","Charapotó"],
                "Bolívar" => ["Calceta","Membrillo","Quiroga"],
                "Chone" => ["Chone","Boyacá","Canuto","Convento","Chibunga","Eloy Alfaro","Ricaurte","San Antonio"],
                "El Carmen" => ["El Carmen","El Limón","Wilfrido Loor Moreira"],
                "Flavio Alfaro" => ["Flavio Alfaro","Zapallo"],
                "Jipijapa" => ["Jipijapa","América","Julcuy","La Unión","Membrillal","Pedro Pablo Gómez","Paján"],
                "Junín" => ["Junín","Ricaurte"],
                "Manta" => ["Manta","Los Esteros","San Mateo","Santa Marianita"],
                "Montecristi" => ["Montecristi","Calderón","Chirijos","La Pila","Leonidas Proaño"],
                "Paján" => ["Paján","Cascol","Guale","Lascano"],
                "Pichincha" => ["Pichincha","Barraganete","El Guanábano","La Unión","San Sebastián"],
                "Rocafuerte" => ["Rocafuerte"],
                "Santa Ana" => ["Santa Ana","La Unión","Lodana","Membrillal"],
                "Sucre" => ["Bahía de Caráquez","Charapotó","Canoa","Leonidas Plaza","San Isidro"],
                "Tosagua" => ["Tosagua","Bachillero","Ángel Pedro Giler"],
                "24 de Mayo" => ["24 de Mayo","Bellavista","Noboa","Pedro Pablo Gómez"],
                "Pedernales" => ["Pedernales","Cojimíes","10 de Agosto","Olmedo","Atahualpa"],
                "Olmedo" => ["Olmedo"],
                "Puerto López" => ["Puerto López","Machalilla","Salango"],
                "Jama" => ["Jama","Tabuga","Don Juan"],
                "Jaramijó" => ["Jaramijó"],
                "San Vicente" => ["San Vicente","Canoa"],
            ],
            "Morona Santiago" => [
                "Morona" => ["Macas","General Proaño","Río Suno","San Isidro","Sevilla Don Bosco","Sinai","Zuña"],
                "Gualaquiza" => ["Gualaquiza","Amazonas","Bomboiza","Chigüinda","El Ideal","Nueva Tarqui","Bermejos"],
                "Limón Indanza" => ["General Leonidas Plaza Gutiérrez","Copal","Chupianza","Indanza","San Antonio","San Miguel de Conchay","Santa Susana de Chiviaza","Yunganza"],
                "Logroño" => ["Logroño","Shimpis","Yaupi"],
                "Morona" => ["Macas","Proaño","Río Suno","San Isidro","Sevilla Don Bosco","Sinaí","Zuña"],
                "Pablo Sexto" => ["Pablo Sexto"],
                "Palora" => ["Palora","Arapicos","Huamboya","Sangay"],
                "Santiago" => ["Méndez","Copal","Chupianza","Patuca","San Luis de El Acho","Santiago","Tayuza","Yampuna"],
                "Sucúa" => ["Sucúa","Asunción","Huambi","Santa Marianita de Jesús"],
                "Huamboya" => ["Huamboya","Chiguaza"],
                "San Juan Bosco" => ["San Juan Bosco","El Rosario","Pan de Azúcar","San Carlos de Limon","San Jacinto de Wakambeis","Santiago de Pananza"],
                "Taisha" => ["Taisha","Huasaga","Macuma","Pumpuentsa","Tuutinentza"],
                "Tiwintza" => ["Santiago","San José de Morona"],
            ],
            "Napo" => [
                "Tena" => ["Tena","Ahuano","Carlos Julio Arosemena Tola","Chonta Punta","Pano","Puerto Misahuallí","Puerto Napo","Talag"],
                "Archidona" => ["Archidona","Cotundo","San Pablo de Ushpayacu"],
                "El Chaco" => ["El Chaco","Linares","Oyacachi","Santa Rosa","Sardinas"],
                "Quijos" => ["Baeza","Cosanga","Cuyuja","Papallacta","San Francisco de Borja"],
                "Carlos Julio Arosemena Tola" => ["Carlos Julio Arosemena Tola"],
            ],
            "Orellana" => [
                "Orellana" => ["Puerto Francisco de Orellana","Dayuma","El Dorado","García Moreno","Inés Arango","La Belleza","Nuevo Paraíso","San José de Guayusa","San Luis de Armenia","Taracoa"],
                "Aguarico" => ["Nuevo Rocafuerte","Capitán Augusto Rivadeneyra","Cononaco","Tiputini","Yasuní"],
                "La Joya de los Sachas" => ["La Joya de los Sachas","Enokanqui","Pompeya","San Carlos","San Sebastián del Coca","Unión Milagreña","Lago San Pedro","Rumipamba","Tres de Noviembre","Virgen del Cisne"],
                "Loreto" => ["Loreto","Ávila Huiruno","Puerto Murialdo","San José de Dahuano","San José de Payamino","San Vicente de Huaticocha"],
            ],
            "Pastaza" => [
                "Pastaza" => ["Puyo","Canelos","Diez de Agosto","Fátima","Montalvo","Pomona","Río Corrientes","Río Tigre","Sarayacu","Simón Bolívar","Tarqui","Teniente Hugo Ortiz","Veracruz","Shell"],
                "Arajuno" => ["Arajuno","Curaray"],
                "Mera" => ["Mera","Madre Tierra","Shell"],
                "Santa Clara" => ["Santa Clara","San José"],
            ],
            "Pichincha" => [
                "Quito" => ["Quito","Alangasí","Amaguaña","Atahualpa","Calacalí","Calderón","Chavezpamba","Checa","El Quinche","Gualea","Guangopolo","Guayllabamba","La Merced","Llano Chico","Lloa","Nanegal","Nanegalito","Nono","Pacto","Perucho","Pifo","Píntag","Pomasqui","Puéllaro","Puembo","San Antonio","San José de Minas","Tababela","Tumbaco","Yaruquí","Zámbiza"],
                "Cayambe" => ["Cayambe","Ascázubi","Cangahua","Cusubamba","Juan Montalvo","Olmedo","Otón","Santa Rosa de Cuzubamba"],
                "Mejía" => ["Machachi","Aloasí","Aloag","Cutuglahua","El Chaupi","Manuel Cornejo Astorga","Tambillo","Uyumbicho"],
                "Pedro Moncayo" => ["Tabacundo","La Esperanza","Malchinguí","Tocachi","Tupigachi"],
                "Rumiñahui" => ["Sangolquí","Cotogchoa","Rumipamba"],
                "San Miguel de los Bancos" => ["San Miguel de los Bancos","Mindo","Pedro Vicente Maldonado","Puerto Quito"],
                "Pedro Vicente Maldonado" => ["Pedro Vicente Maldonado"],
                "Puerto Quito" => ["Puerto Quito"],
            ],
            "Santa Elena" => [
                "Santa Elena" => ["Santa Elena","Atahualpa","Colonche","Chanduy","Manglaralto","Simón Bolívar","Salinas"],
                "La Libertad" => ["La Libertad"],
                "Salinas" => ["Salinas","Anconcito","José Luis Tamayo"],
            ],
            "Santo Domingo de los Tsáchilas" => [
                "Santo Domingo" => ["Santo Domingo","El Esfuerzo","Luz de América","San Jacinto del Búa","Santa María del Toachi","Valle Hermoso"],
            ],
            "Sucumbíos" => [
                "Nueva Loja" => ["Nueva Loja","Dureno","El Eno","General Farfán","La Bermeja","Pacayacu","Palma Roja","Santa Cecilia","Sevilla","Shushufindi","Tarapoa"],
                "Cascales" => ["El Dorado de Cascales","Sevilla","Santa Rosa de Sucumbíos"],
                "Cuyabeno" => ["Tarapoa","Aguas Negras","Cuyabeno","Lagartococha"],
                "Gonzalo Pizarro" => ["Lumbaquí","El Reventador","Monte Olivo","Puerto Libre"],
                "Putumayo" => ["Puerto El Carmen de Putumayo","Palma Roja","Puerto Bolívar","Rosa Florida","San Roque","Santa Elena","Teniente Hugo Ortiz"],
                "Shushufindi" => ["Shushufindi","Limoncocha","Pañacocha","San Pedro de los Cofanes","San Roque","Siete de Julio"],
                "Sucumbíos" => ["La Bonita","El Playón de San Francisco","La Sofía","Rosa Florida","Santa Bárbara"],
            ],
            "Tungurahua" => [
                "Ambato" => ["Ambato","Atocha-Ficoa","Celiano Monge","Huachi Chico","Huachi Grande","Izamba","Juan Benigno Vela","La Merced","La Península","Picaigua","Pinllo","Quisapincha","San Bartolomé de Pinllo","San Francisco","Santa Rosa","Totoras","Pasa","Pilahuin","Constantino Fernández","Augusto N. Martínez"],
                "Baños de Agua Santa" => ["Baños de Agua Santa","Lligua","Río Negro","Río Verde","Ulba"],
                "Cevallos" => ["Cevallos"],
                "Mocha" => ["Mocha","Pinguilí"],
                "Patate" => ["Patate","El Triunfo","Los Andes","Sucre"],
                "Quero" => ["Quero","Chicauma","Rumipamba"],
                "San Pedro de Pelileo" => ["Pelileo","Benítez","Bolívar","Cotaló","Chiquicha","El Rosario","García Moreno","Guambaló","Huambalo"],
                "Santiago de Píllaro" => ["Píllaro","Emilio María Terán","Marcos Espinel","Presidente Urbina","San Andrés","San José de Poaló","San Miguelito"],
                "Tisaleo" => ["Tisaleo","Quinchicoto"],
            ],
            "Zamora Chinchipe" => [
                "Zamora" => ["Zamora","Cumbaratza","El Pangui","Guadalupe","Imbana","Sabanilla","Timbara","Yacuambi"],
                "Chinchipe" => ["Zumba","Chito","El Chorro","La Chonta","Pucapamba","San Andrés","Tnte. Jorge Riofrio"],
                "El Pangui" => ["El Pangui","El Guismi","Pachicutza","Tundayme"],
                "Nangaritza" => ["Guayzimi","Nuevo Paraíso","Zurmi"],
                "Palanda" => ["Palanda","El Porvenir del Carmen","San Francisco de Vergel","Valladolid"],
                "Paquisha" => ["Paquisha","Bellavista","Nuevo Quito"],
                "Yacuambi" => ["28 de Mayo","La Paz","Tutupali"],
                "Yantzaza" => ["Yantzaza","Chicaña","Los Encuentros"],
                "Centinela del Cóndor" => ["Zumbi","Panguintza","El Alamo"],
            ],
        ];

        $json = json_encode($ubicaciones, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT);
        file_put_contents(resource_path('js/data/ecuador.json'), $json);

        $this->info('Archivo ecuador.json generado correctamente en resources/js/data/');
    }
}